### ISSUE TITLE
Read new birth data into the warehouse

### ISSUE THREAD

**Issue by rpitingolo** [NeighborhoodInfoDC/Vital#10]
We received 3 files from DOH for years 2003-2016 and need to run these through the system so that each individual year is saved as a dataset and dummy variables created for each. 

The previous way of doing this was to use %Read_births. If the new data is similar in format to the old data we might be able to use it with some updates. Otherwise, it might be more efficient to create a new macro for reading in the data and creating the dummy variables. 

After creating datasets for each year we will have to think about the best way to summarize the data given that we have address points now. The old system of summarizing from tracts probably isn't best.

cc: @ptatian

**Comment by ptatian** [comment]
@maggiesu0725 As I mentioned to @rpitingolo yesterday, I've done some work with the birth (and death) data for the DC report on African Americans. You may find it helpful to [look at the code I used](https://github.com/NeighborhoodInfoDC/DCOLA/blob/master/Prog/SOIAA2018/Tables_births_soiaa_2018.sas), which I adapted from our older code, when updating the birth programs. 

A few things to note. 
- The _Black_ variable was purely for the DC report and does not need to be replicated in the new Births data sets. 
- The _Pre_care_ var does not exist in the 2010-16 data. I had to calculate it because it is needed to create the prenatal care variables. 
- There's extensive missing data in 2009 for all of the prenatal care variables, so it's better not to create those variables at all in that year. 
- I changed low birth weight from < 5.5 lbs to < 2,500 grams, which seems to be the [modern standard](http://www.chop.edu/conditions-diseases/low-birthweight). 

Output tables from the program are on L:. I hope that's helpful. Let me know if you have any questions.

**Comment by ptatian** [comment]
@rpitingolo How many are there, compared to the total?

**Comment by rpitingolo** [comment]
In the 2010 - 2016 data it's 90 out of about 66k.

**Comment by ptatian** [comment]
OK, then I would drop them.

**Comment by rpitingolo** [comment]
@ptatian OK. Thanks.
