### ISSUE TITLE
Read new death data into the warehouse

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Vital#13]
We received 2 files from DOH for years 2003-2016 and need to run these through the system so that each individual year is saved as a data set and dummy variables created for each. That is, recreate the existing **Vital.Deaths_????** data sets and expand to include later years. 

Existing death SAS data sets should be copied to a ZIP file in the Data folder before beginning. 

For the new data, we will use geocoded addresses to assign records to standard geographic areas, rather than the previous tract remapping process. 

I've worked with the new death files for a recent DC report. [The code I used](https://github.com/NeighborhoodInfoDC/DCOLA/blob/master/Prog/SOIAA2018/Tables_deaths_soiaa_2018.sas), which is based on our previous death data code, could be helpful when revising the programming for the new data. A few things to note.

- Please review all of my code as I did not have time to do extensive checking. 
- The _Black_ variable was purely for the DC report and does not need to be replicated in the new Births data sets.
- Date-related vars need extensive checking and cleaning.
- The age at death calculation is complicated, perhaps too complicated. My preference was to calculate age based on death date minus birth date, but that didn't always give good results. You should review my code to see if it can be simplified. 
- Cause of death codes for all of the new files are ICD10. No need to use ICD9.

Output tables from my program are in **L:\Libraries\DCOLA\Prog\SOIAA2018\Tables_deaths_SOIAA_2018.rtf**. I hope that's helpful. Let me know if you have any questions.

@rpitingolo Assigning this to you initially. You can reassign some or all the work to someone else, at your discretion.

**Comment by rpitingolo** [comment]
@ptatian I took a look at the raw death data. There are a couple significant differences between the two files.

1. The 2003-2008 file has no variable for ethnicity. It appears from the metadata that the death data we have in the warehouse now has ethnicity going back to 2001. 
2. The 2003-2008 file has addresses formatted in a weird way. For example it has "M ST 2100 NW 20037" Instead of "2100 M ST NW 20037". It almost looks like the address data was previously broken out into different components, and someone concatenated them into a single variable but in the wrong order. 

On the first issue, the question is whether to keep the data we have in the warehouse now, which might be less geographically precise but has ethnicity, or update the data going back to 2003 for geographic precision but lose ethnicity. Perhaps there's another option but not an easy one as far as I can tell. Regardless, we still need to process a 2008 file and that one won't have ethnicity. 

On the second issue, we'll need to parse out the pieces of the address and re-arrange it in a way that the geocoder can interpret, assuming the current order won't work. Not impossible but will require a bit of coding to get it. 

cc: @maggiesu0725

**Comment by ptatian** [comment]
Thanks, @rpitingolo. When you say ethnicity, do you mean the var indicating Hispanic origin (Latino)? Does the 2003-2008 file have a race var? This may be something we should ask DOH about.

**Comment by rpitingolo** [comment]
FYI I was able to geocode about 97% of the records in the 2009-2016 file. Some of the records that didn't geocode have tract information. Unfortunately due to inconsistent formatting from one year to the next I'm going to have to do some cleanup before I run it through %tr10_to_stdgeos. That will still leave a chunk (~500 records) with missing geographic info. I may try to use the hot deck macro to take care of those. 

@maggiesu0725 @ptatian

**Comment by ptatian** [comment]
Thanks, @rpitingolo. 500 records is insignificant at this stage. Let's push on and do the cleanup later.

**Comment by lhendey** [comment]
@rpitingolo - can this be closed (or move clean up to new issues?) cc @ptatian

**Comment by rpitingolo** [comment]
Yes. This is done.
